Algoritmo "exe8_parafaca"
// Disciplina   : [Linguagem e L?gica de Programa??o]
// Professor   : Hiram Amaral
// Descri??o   : Aqui voc? descreve o que o programa faz! (fun??o)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/03/2022
Var
// Se??o de Declara??es das vari?veis
     contador: inteiro

Inicio
// Se??o de Comandos, procedimento, fun??es, operadores, etc...


  para contador de 1 ate 10 faca
  escreva(contador)
  fimpara

Fimalgoritmo