Algoritmo "EX_aula_6"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Reinaldo Gabriel
// Data atual  : 04/04/2022
Var:

   base, altura, area : Real

Inicio

   Escreva("Base: ")

   Leia(base)

   Escreva("Altura: ")

   Leia(altura)

   area <- (base * altura) / 2

   escreval("Área do Triângulo: ", area)

Fimalgoritmo