Algoritmo "exercicio 10"
// Disciplina  :  [Lógica de Programação - I.A] 
// Professor   : Hiram Amaral 
// Descrição   : Exemplo de procedimento
// Autor(a)    : Giovanna Cavalcante
// Data atual  : 12/04/2022
Var
// Seção de Declarações das variáveis 
x,y,res: inteiro

inicio

// res é variável global
res <- x + y
escreval("Digite um número:")
leia(x)
escreval("Digite outro número:")
leia(y)
res <- x + y
escreval("O resultado é:", res)

Fimalgoritmo