Algoritmo "exe7_nomecompleto"
// Disciplina : [Linguagem e Lógica de Programa??o]
// Professor : Hiram Amaral
// Descri??o : Aqui voc? descreve o que o programa faz! (diversão??o)
// Autor(a): alunocetam
// Dados atuais: 25/03/2022
Var
// Se??o de Declara??es das vari?veis
   nome, snome, completo: caractere
InIcio
// Se??o de Comandos, procedimento, fun??es, operadores, etc...
   escreva("Digite seu nome")
   leia(nome)

   escreva("Digite seu sobrenome")
   leia(snome)

   //NOME COMPLETO

   escreva(completo)

Fimalgoritmo