algoritmo "ex10"
// Função : A Loja Mamão com Açúcar está vendendo seus produtos em 5 //(cinco) prestações sem juros. Faça um algoritmo que
// receba um valor de uma compra e mostre o valor das prestações. // Seção de Declarações
var
   compra, prestacao: real
inicio
   // Seção de Comandos
   escreval("========== Loja Mamão com Açúcar ==========")
   escreva("Digite o valor da compra: ")
   leia(compra)
   prestacao<-compra/5
    escreval("o valor da pestação R$ ", prestacao)

Fimalgoritmo
