Algoritmo "semnome"
// Disciplina   : [Linguagem e L?gica de Programa??o]
// Professor   : Hiram Amaral
// Descri??o   : soma  (fun??o)
// Autor(a)    : Pedro
// Data atual  : 31/03/2022
Var
// Se??o de Declara??es das vari?veis
x, y : inteiro

Inicio
// Se??o de Comandos, procedimento, fun??es, operadores, etc...

escreval("Digite primeiro numero:")
leia(x)
escreval("Digite segundo numero:")
leia(y)

escreval("Resultado da soma desses numeros ser?: ",x+y)

Fimalgoritmo