Algoritmo "exe8_parafaca"
// Disciplina : [Linguagem e Lógica de Programa??o]
// Professor : Hiram Amaral
// Descri??o : Aqui voc? descreve o que o programa faz! (diversão??o)
// Autor(a): Nome do(a) aluno(a)
// Dados atuais: 25/03/2022
Var
// Se??o de Declara??es das vari?veis
    //contador inteiro

InIcio
// Se??o de Comandos, procedimento, fun??es, operadores, etc...


  //para contador de 1 a 10 faca
 // escreva(contador)
  //fimpara

Fimalgoritmo