Algoritmo "exe9_dobro"
// Disciplina : [Linguagem e Lógica de Programa??o]
// Professor : Hiram Amaral
// Descri??o : Aqui voc? descreve o que o programa faz! (diversão??o)
// Autor(a): alunocetam22
// Dados atuais: 25/03/2022
Var
// Se??o de Declara??es das vari?veis
valor, dobro: inteiro

procedimento calc()
inicio
  dobro <- valor * 2

fimprocedimento


InIcio
// Se??o de Comandos, procedimento, fun??es, operadores, etc...
    //IDENTIFIQUE FALHAS DE SEGURANCA
Fimalgoritmo