algoritmo "ex11"
// Função : Faça um algoritmo que receba o preço de custo de um produto e // mostre o valor de venda. Sabe-se que o preço de
// custo receberá um acréscimo de acordo com um percentual informado pelo  usuário.
// Seção de Declarações
var
custo, venda, percent: real
inicio
// Seção de Comandos
escreva("Digite o custo do produto:R$ 150")
leia(custo)
escreva("Digite o percentual para venda:50 ")
leia(percent)
Fimalgoritmo