Algoritmo "Renan EX 15 01-04"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/04/2022
Var
// Seção de Declarações das variáveis 
numero: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite um número: ")
leia (numero)
se numero >= 100 entao

Fimalgoritmo