Algoritmo "Soma entre dois números (Ex1)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral
// Descrição   : Soma dois números
// Autor(a)    : Thiago
// Data atual  : 29/03/2022
Var
   x, y: Inteiro
   soma: inteiro

Inicio
   Escreval("Escolha dois números:")
   Escreval("Primeiro número")
   Leia(x)
   Escreval("Segundo número")
   Leia(y)
   soma <- x + y
   Escreval("A soma entre os números ", x, " e", y, " é igual à:", soma )

Fimalgoritmo
