Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Thiago
// Data atual  : 01/04/2022
Var
// Seção de Declarações das variáveis
     contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...


  para contador de 1 ate 10 faca
  escreva(contador)
  fimpara

Fimalgoritmo
