Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/04/2022
Var
// Seção de Declarações das variáveis 
valor, dobro: inteiro

Inicio
Escreval("Digite um número inteiro: ")
leia(valor)
dobro <- valor * 2
Escreva("O dobro desse inteiro é: ", dobro)
Fimalgoritmo