Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/04/2022
Var
n, sn, nc: caractere
//nome, sobrenome e nome completo
Inicio
Escreval("Escreva seu nome: ")
leia(n)
Escreval("Escreval seu sobrenome; ")
leia(sn)

nc <- n + " " + sn

escreval("Seu nome é ", nc, "!")


Fimalgoritmo