Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/04/2022
// Seção de Declarações das variáveis
VAR
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...


   enquanto (contador < 11) faca
      escreva(contador)
      contador <- contador + 1
      fimenquanto

Fimalgoritmo