Algoritmo "apresentaNumeros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : HIRAM AMARAL
// Descrição   : APRESENTA NUMEROS DE 0 À 10
// Autor(a)    : MARCELO BILBY BARBOSA
// Data atual  : 27/04/2022
Var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
repita
  escreva (contador)
  contador <- contador + 1
  ate (contador > 10)

Fimalgoritmo