Algoritmo " ex 2 calcular x,y"
// função:faça um algoritimo que receba dois numeros e ao final mostre a
 //soma,subtração,multiplicação e a divisão dos numeros lidos
 //Seção de Declarações
Var
x,y:real

Inicio
//Seção de comandos
escreva("Digite o primriro numero:")
leia(x)
escreva("Digite o segundo numero:")
leia(y)
escreval("a soma é:",x+y)
escreval("A subtrção é:",x-y)
escreval("multiplicação é:",x*y)
escreval("A divisão é:",x/y)
Fimalgoritmo
