Algoritmo "IGOR EXERCÍCIO 01 29-03"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral
// Descrição   : SOMA DE DOIS NÚMEROS
// Autor(a)    : IGOR ALVARENGA
// Data atual  : 29/03/2022
Var
   //
   x, y: inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("DIGITE O PRIMEIRO NÚMERO: " )
   leia(X)
   escreval("DIGTE O SEGUNDO NÚMERO: ")
   leia (y)
   escreva("A SOMA DOS DOIS NÚMEROS É: ", X+Y)
Fimalgoritmo