Algoritmo "altura"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : maycon
// Data atual  : 08/04/2022
Var
// Seção de Declarações das variáveis 
a,b,X:real
inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval("valor da base: ")
  leia(A)
  escreval("VALOR DA ALTURA : ")
  leia(B)
   X <- (A*B)
  escreval("O valor de x é:n ",x)
Fimalgoritmo