Algoritmo "ex1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Faça um algoritmo que receba dois números e exiba o resultado da sua  soma.
// Autor(a)    : Edicleia
// Data atual  : 31/03/2022
Var
x,y: Inteiro


Inicio
escreval("Digite o primeiro número: ")
leia(x)
escreval("Digite o segundo número: ")
leia(y)
escreval("A soma dos números é: ",x+y)
escreval(" --------------------------")



Fimalgoritmo

