Algoritmo "Número"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Maria Fernanda
// Data atual  : 4/1/2022
Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva("Digite um numero:")
    leia(numero)
    se numero > 10 entao
    escreval("O numero é maior que 10")
    fimse

Fimalgoritmo