Algoritmo "Custo de uma Fábrica"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/1/2022
Var
// Seção de Declarações das variáveis 
custoFabrica, custoFinal: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Informe o custo de fabrica de veiculo:")
   leia(custoFabrica)
   custoFinal

Fimalgoritmo