Algoritmo"algoritomo repita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/04/2022
Var
// Seção de Declarações das variáveis 
 a:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("digite um numero inteiro menor que 10:")
 leia(a)
   repita
   a<- a+1
    escreval(a)
  ate(a>10)
Fimalgoritmo